# Generated by Django 4.0.5 on 2023-01-20 22:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=50)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(upload_to='noticia/%Y/%m/%d')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.CharField(blank=True, max_length=200, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seccion')),
            ],
        ),
    ]
