# Generated by Django 4.0.5 on 2023-01-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seccion_noticia1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
