# Generated by Django 4.0.5 on 2023-01-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia1',
            name='enlace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
