# Generated by Django 4.0.5 on 2023-01-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_noticia_autor_perfil_gmail_perfil_ig_perfil_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='es_portada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='profilepic',
            field=models.ImageField(default='inicio.png', upload_to='profile_pics/%Y/%m'),
        ),
    ]
