# Generated by Django 4.0.5 on 2023-01-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_noticia1_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia1',
            name='imagen',
            field=models.ImageField(upload_to='noticia/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='noticia1',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
