# Generated by Django 4.0.5 on 2023-01-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_autor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user_personalizado'),
        ),
    ]
