# Generated by Django 4.0.5 on 2023-01-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_personalizado_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_personalizado',
            name='es_autor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_personalizado',
            name='es_editor',
            field=models.BooleanField(default=False),
        ),
    ]
