# Generated by Django 4.0.5 on 2023-01-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_imagen_noticia_portada_noticia_pie_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_personalizado',
            name='profilepic',
            field=models.ImageField(default='inicio.png', upload_to='user_directory_path'),
        ),
    ]
