# Generated by Django 4.0.5 on 2023-01-25 21:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_personalizado_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_personalizado',
            name='profilepic',
            field=models.ImageField(default='inicio.png', upload_to=core.models.User_personalizado.user_directory_path),
        ),
    ]
