# Generated by Django 4.0.5 on 2023-01-28 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_autor_options_alter_editor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='es_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user_personalizado')),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='comentarios',
            field=models.ManyToManyField(to='core.comentarios'),
        ),
    ]
