# Generated by Django 4.0.5 on 2023-01-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_noticia_es_visible_comentarios_noticia_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user_personalizado'),
        ),
    ]
