# Generated by Django 4.0.5 on 2023-01-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_usuario_comentarios_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='noticia',
        ),
    ]
