# Generated by Django 4.0.5 on 2023-01-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_comentarios_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.noticia'),
        ),
    ]
