# Generated by Django 4.0.5 on 2023-02-02 20:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_alter_comentarios_options_comentarios_es_visible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_personalizado',
            new_name='Perfil',
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
