# Generated by Django 4.0.5 on 2023-02-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_user_personalizado_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='enlace',
        ),
    ]
