# Generated by Django 4.0.5 on 2023-02-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_noticia_enlace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
